apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescale-topo-lvm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topolvm-provisioner
  resources:
    requests:
      storage: 1Gi

