apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescale-local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

